name: Lint
on:
  - workflow_dispatch
  - workflow_call
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Lint
        run: |
          npm install
          npm run lint
